### ISSUE TITLE
Falta colocar a função srand();

### ISSUE THREAD

**Issue by DavidGomesh** [JulioEvencio/sistema_de_loja#1]
# Função srand();
A função srand(), vai setar a semente para a geração do número.
Mas você precisa usar a função:
```c
time(NULL);
```
Da biblioteca:
```c
#include <time.h>
```
Você vai usar da seguinte forma:
```c
int num;
srand(time(NULL));
num = rand();
```

**Comment by JulioEvencio** [comment]
> # Função srand();
> A função srand(), vai setar a semente para a geração do número.
> Mas você precisa usar a função:
> 
> ```c
> time(NULL);
> ```
> 
> Da biblioteca:
> 
> ```c
> #include <time.h>
> ```
> 
> Você vai usar da seguinte forma:
> 
> ```c
> int num;
> srand(time(NULL));
> num = rand();
> ```

Não vou mais utilizar a função srand
