### ISSUE TITLE
Crie branches!

### ISSUE THREAD

**Issue by DavidGomesh** [JulioEvencio/sistema_de_loja#2]
#  Crie uma branch para cada nova funcionalidade
**Por exemplo:**
- localizar-produto
    -  correcao-localizar-produto
- excluir-produto

**Comment by JulioEvencio** [comment]
> # Crie uma branch para cada nova funcionalidade
> **Por exemplo:**
> 
> * localizar-produto
>   
>   * correcao-localizar-produto
> * excluir-produto

Acabei de adicionar novas coisas e só lembrei das branchs agora que vi sua issues kkkk. Da próxima vez ficarei mais atento

**Comment by DavidGomesh** [comment]
> > # Crie uma branch para cada nova funcionalidade
> > **Por exemplo:**
> > 
> > * localizar-produto
> >   
> >   * correcao-localizar-produto
> > * excluir-produto
> 
> Acabei de adicionar novas coisas e só lembrei das branchs agora que vi sua issues kkkk. Da próxima vez ficarei mais atento

**Beleza mano!**
Tô vendo que você está trabalhando bem no seu código! Parabéns! Desculpa a demora pra responder, mas tô usando o app do GitHub, e ele simplesmente não notificou sua resposta. Continua programando, quando meu computador chegar do conserto, vou poder olhar melhor o seu código.
