### ISSUE TITLE
Novo Sistema de Armazenamento de Histórico

### ISSUE THREAD

**Issue by DavidGomesh** [JulioEvencio/sistema_de_loja#3]
# Armazenamento de Histórico - Branch: Corrigindo_bugs-gomesh
## Nova _**Struct**_ para armazenar o histórico:
```c
typedef struct tipo_historico{
    char descricao[101];
}Historico;

Historico historico[100];
```
Um vetor do tipo ```Historico```, com a possibilidade de armazenar 100 operações.
- Futuramente, pode ser adicionado outros dados para o histórico armazenar, como data e hora da operação.
## Remoção do parâmetro  ```int historico``` desnecessário em funções:
![image](https://user-images.githubusercontent.com/53452408/84516527-4c1ffc00-aca4-11ea-8906-c4ecb0417ab9.png)
## Função ```int verificador_de_historico(void);``` alterada:
```c
int verificador_de_historico(void)
{
    int i;
    for(i=0; i<100; i++){
        if(strcmp(historico[i].descricao, "")==0){
            return i;
        }
    }
    return -1;
}
```
A função procura alguma posição que esteja vazia na struct ```historico```.
Caso encontrar retorna essa posição, caso contrário retorna o valor inválido ```-1```.
## Função ```strlen(string);```:
Definida na biblioteca:
```c
#include <string.h>
```
A função:
```c
strlen(string);
```
Retorna o tamanho de uma string (retorna um valor do tipo ```int```). Por isso seu uso geralmente vem acompanhado de uma variável, por exemplo:
```c
#include <stdio.h>
#include <string.h>

int main(){
    char nome[31] = "Gomesh\0";
    int tamanho = strlen(nome);
    printf("Tamanho: %i\n", tamanho);
    return 0;
}
```
A saída desse programa será ```7```, visto que, o caractere nulo ```'\0'``` também será contabilizado.
## Processo de armazenamento do histórico:
Primeiramente, é criado uma variável que receba a posição disponível para armazenar o histórico:
```c
int i = verificador_de_historico();
```
Depois, dois vetores auxiliares são criados:
```c
char informacao[101];
char produto_nome[101];
```
Então, o vetor que guarda o nome do produto é preenchido, e tratado, tirando da sua última posição utilizada o caractere nulo ```'\0'```, e adicionando um espaço ```' '```:
```c
strcpy(produto_nome, produto[posicao].nome);
int tam = strlen(produto_nome);
produto_nome[tam-1]=' ';
```
Por fim, o nome do produto e a mensagem a ser guardada, são concatenados no vetor ```char informacao[101];```, e posteriormente adicionados no histórico:
```c
strcpy(informacao, produto_nome);
strcat(informacao, "foi adicionado\0");

strcpy(historico[i].descricao, informacao);
```
**Obs.:** A mensagem se difere em cada situação.
### Código completo:
```c
int i = verificador_de_historico();
char informacao[101];
char produto_nome[101];

strcpy(produto_nome, produto[codigo].nome);
int tam = strlen(produto_nome);
produto_nome[tam-1]=' ';

strcpy(informacao, produto_nome);
strcat(informacao, "foi alterado\0");

strcpy(historico[i].descricao, informacao);
```
## Função ```void printar_historico(void);```:
Essa função exibe todos os históricos armazenados:
```c
void printar_historico(void)
{
    int loop;
    printf("========HISTORICO======== \n");
    for(loop = 0; loop < 100; loop++)
    {
        if(strcmp(historico[loop].descricao, "") != 0)
        {
            printf("%s\n", historico[loop].descricao);
        }
    }
}
```
### Um exemplo de sua saída:
![image](https://user-images.githubusercontent.com/53452408/84519380-63f97f00-aca8-11ea-8b9f-350b822e1f87.png)
## Problemas a serem corrigidos:
- O programa não trata do erro, caso o ```verificador_de_historico(void);``` retornar ```-1```;
- Há códigos repetidos nos processos de armazenamento de históricos;
  - O processo de armazenamento de histórico é praticamente igual em todos os casos, só muda os valores. Então, o correto a se fazer é: criar uma função que seja chamada toda vez que esse processo seja necessário. A função receberia como parâmetros o produto em questão e a mensagem a ser armazenada.

**Comment by DavidGomesh** [comment]
# No excluir apresentou um problema
Agora que percebi que na saída só apareceu _"foi excluido"_, não mostrou o nome do produto excluído.

**Comment by JulioEvencio** [comment]
> # No excluir apresentou um problema
> Agora que percebi que na saída só apareceu _"foi excluido"_, não mostrou o nome do produto excluído.

Sim, deve ser porque você copiou o nome depois de apagar. Aqui no meu eu fiz a copia antes disso e ta normal

**Comment by JulioEvencio** [comment]
> # Armazenamento de Histórico - Branch: Corrigindo_bugs-gomesh
> ## Nova _**Struct**_ para armazenar o histórico:
> ```c
> typedef struct tipo_historico{
>     char descricao[101];
> }Historico;
> 
> Historico historico[100];
> ```
> 
> Um vetor do tipo `Historico`, com a possibilidade de armazenar 100 operações.
> 
> * Futuramente, pode ser adicionado outros dados para o histórico armazenar, como data e hora da operação.
> 
> ## Remoção do parâmetro `int historico` desnecessário em funções:
> ![image](https://user-images.githubusercontent.com/53452408/84516527-4c1ffc00-aca4-11ea-8906-c4ecb0417ab9.png)
> 
> ## Função `int verificador_de_historico(void);` alterada:
> ```c
> int verificador_de_historico(void)
> {
>     int i;
>     for(i=0; i<100; i++){
>         if(strcmp(historico[i].descricao, "")==0){
>             return i;
>         }
>     }
>     return -1;
> }
> ```
> 
> A função procura alguma posição que esteja vazia na struct `historico`.
> Caso encontrar retorna essa posição, caso contrário retorna o valor inválido `-1`.
> 
> ## Função `strlen(string);`:
> Definida na biblioteca:
> 
> ```c
> #include <string.h>
> ```
> 
> A função:
> 
> ```c
> strlen(string);
> ```
> 
> Retorna o tamanho de uma string (retorna um valor do tipo `int`). Por isso seu uso geralmente vem acompanhado de uma variável, por exemplo:
> 
> ```c
> #include <stdio.h>
> #include <string.h>
> 
> int main(){
>     char nome[31] = "Gomesh\0";
>     int tamanho = strlen(nome);
>     printf("Tamanho: %i\n", tamanho);
>     return 0;
> }
> ```
> 
> A saída desse programa será `7`, visto que, o caractere nulo `'\0'` também será contabilizado.
> 
> ## Processo de armazenamento do histórico:
> Primeiramente, é criado uma variável que receba a posição disponível para armazenar o histórico:
> 
> ```c
> int i = verificador_de_historico();
> ```
> 
> Depois, dois vetores auxiliares são criados:
> 
> ```c
> char informacao[101];
> char produto_nome[101];
> ```
> 
> Então, o vetor que guarda o nome do produto é preenchido, e tratado, tirando da sua última posição utilizada o caractere nulo `'\0'`, e adicionando um espaço `' '`:
> 
> ```c
> strcpy(produto_nome, produto[posicao].nome);
> int tam = strlen(produto_nome);
> produto_nome[tam-1]=' ';
> ```
> 
> Por fim, o nome do produto e a mensagem a ser guardada, são concatenados no vetor `char informacao[101];`, e posteriormente adicionados no histórico:
> 
> ```c
> strcpy(informacao, produto_nome);
> strcat(informacao, "foi adicionado\0");
> 
> strcpy(historico[i].descricao, informacao);
> ```
> 
> **Obs.:** A mensagem se difere em cada situação.
> 
> ### Código completo:
> ```c
> int i = verificador_de_historico();
> char informacao[101];
> char produto_nome[101];
> 
> strcpy(produto_nome, produto[codigo].nome);
> int tam = strlen(produto_nome);
> produto_nome[tam-1]=' ';
> 
> strcpy(informacao, produto_nome);
> strcat(informacao, "foi alterado\0");
> 
> strcpy(historico[i].descricao, informacao);
> ```
> 
> ## Função `void printar_historico(void);`:
> Essa função exibe todos os históricos armazenados:
> 
> ```c
> void printar_historico(void)
> {
>     int loop;
>     printf("========HISTORICO======== \n");
>     for(loop = 0; loop < 100; loop++)
>     {
>         if(strcmp(historico[loop].descricao, "") != 0)
>         {
>             printf("%s\n", historico[loop].descricao);
>         }
>     }
> }
> ```
> 
> ### Um exemplo de sua saída:
> ![image](https://user-images.githubusercontent.com/53452408/84519380-63f97f00-aca8-11ea-8b9f-350b822e1f87.png)
> 
> ## Problemas a serem corrigidos:
> * O programa não trata do erro, caso o `verificador_de_historico(void);` retornar `-1`;
> * Há códigos repetidos nos processos de armazenamento de históricos;
>   
>   * O processo de armazenamento de histórico é praticamente igual em todos os casos, só muda os valores. Então, o correto a se fazer é: criar uma função que seja chamada toda vez que esse processo seja necessário. A função receberia como parâmetros o produto em questão e a mensagem a ser armazenada.

Funcionou agora!!!
Fiz quase tudo que foi sugerido menos a modificação do verificador_de_historico().
No caso do jeito que você fez sempre que o histórico ficar cheio será retornado -1. No caso do jeito antigo sempre que o histórico ficar cheio ele reescreve as novas descrições nas mais antigas. Acho que dessa forma fica bem mais interessante, pois isso evita que o usuário tenha que ficar excluindo o histórico de tempo em tempo.

**Comment by DavidGomesh** [comment]
@JulioEvencio 
Tudo bem! Fica bom mesmo!
Mas tenho uma dúvida: como o histórico será exibido?

Pq atualmente histórico é exibido assim (levando em consideração que o máximo de operações que o histórico suporta é cinco):
1° operação
2° operação
3° operação
4° operação
5° operação

Caso a lista fique cheia, e mais duas operações tenham sido realizadas, o histórico seria exibido assim:
6° operação
7° operação
3° operação
4° operação
5° operação

O que me parece um pouco estranho. Acho que vc poderia tentar deixar assim:
3° operação
4° operação
5° operação
6° operação
7° operação

Ficaria melhor!

**Comment by JulioEvencio** [comment]
> @JulioEvencio
> Tudo bem! Fica bom mesmo!
> Mas tenho uma dúvida: como o histórico será exibido?
> 
> Pq atualmente histórico é exibido assim (levando em consideração que o máximo de operações que o histórico suporta é cinco):
> 1° operação
> 2° operação
> 3° operação
> 4° operação
> 5° operação
> 
> Caso a lista fique cheia, e mais duas operações tenham sido realizadas, o histórico seria exibido assim:
> 6° operação
> 7° operação
> 3° operação
> 4° operação
> 5° operação
> 
> O que me parece um pouco estranho. Acho que vc poderia tentar deixar assim:
> 3° operação
> 4° operação
> 5° operação
> 6° operação
> 7° operação
> 
> Ficaria melhor!

Realmente, não tinha pensado nisso, vou tentar fazer algo aqui

**Comment by DavidGomesh** [comment]
@JulioEvencio ok!

**Comment by JulioEvencio** [comment]
> @JulioEvencio
> Tudo bem! Fica bom mesmo!
> Mas tenho uma dúvida: como o histórico será exibido?
> 
> Pq atualmente histórico é exibido assim (levando em consideração que o máximo de operações que o histórico suporta é cinco):
> 1° operação
> 2° operação
> 3° operação
> 4° operação
> 5° operação
> 
> Caso a lista fique cheia, e mais duas operações tenham sido realizadas, o histórico seria exibido assim:
> 6° operação
> 7° operação
> 3° operação
> 4° operação
> 5° operação
> 
> O que me parece um pouco estranho. Acho que vc poderia tentar deixar assim:
> 3° operação
> 4° operação
> 5° operação
> 6° operação
> 7° operação
> 
> Ficaria melhor!

Problema corrigido!
